### ISSUE TITLE
fails to compile on OTEL version 1.39 as 

### ISSUE THREAD

**Issue by nagkumar** [elastic/observability-examples#40]
https://github.com/elastic/observability-examples/blob/main/Elastiflix/java-favorite-otel-manual/src/main/java/com/movieapi/FavoriteApplication.java

FavoriteApplication.java:[5,33] cannot find symbol
19.73 [ERROR]   symbol:   class GlobalLoggerProvider

Pl. update to latest
